config/routes.rb
Rails.application.routes.draw do

  root to: 'users#sign_in'
  
  scope path: '/users', controller: :users do
    get 'sign_in' => :sign_in, as: 'login'
    post 'create_session' => :create_session, as: 'create_session'
    get 'logout' => :logout
  end

  scope accounts: '/accounts', controller: :accounts do
    get 'new' => :new, as: 'new_account'
    post 'create' => :create, as: 'create_account'
  end

  scope path: '/dashboard', controller: :dashboard do
    get 'show' => :show, as: 'dashboard_show'
  end

  scope path: '/streams', controller: :streams do
    get 'show' => :show, as: 'show_streams'
    get 'new' => :new, as: 'new_stream'
    post 'create' => :create, as: 'create_stream'
  end

  scope path: '/remote_devices', controller: :remote_devices do
    post 'create' => :create, as: 'create_remote_device'
  end

  scope path: '/api', controller: :data do
    post 'new_data' => :create
    post 'telegram' => :index
    post 'telegram_devices' => :devices
  end


end

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= @current_user.name %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", dashboard_show_path %></li>
        <li><%= link_to "Streams", show_streams_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Logout", logout_path%></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>