config/routes.rb
Rails.application.routes.draw do

  root to: 'users#sign_in'
  
  scope path: '/users', controller: :users do
    get 'sign_in' => :sign_in, as: 'login'
    post 'create_session' => :create_session, as: 'create_session'
    get 'logout' => :logout
  end

  scope accounts: '/accounts', controller: :accounts do
    get 'new' => :new, as: 'new_account'
    post 'create' => :create, as: 'create_account'
  end

  scope path: '/dashboard', controller: :dashboard do
    get 'show' => :show, as: 'dashboard_show'
  end

  scope path: '/streams', controller: :streams do
    get 'show' => :show, as: 'show_streams'
    get 'new' => :new, as: 'new_stream'
    post 'create' => :create, as: 'create_stream'
  end

  scope path: '/remote_devices', controller: :remote_devices do
    post 'create' => :create, as: 'create_remote_device'
  end

  scope path: '/api', controller: :data do
    post 'new_data' => :create
    post 'telegram' => :index
    post 'telegram_devices' => :devices
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_account_relations
  has_many :accounts, through: :user_account_relations
  
  has_secure_password

  validates :name, :email, :username, presence: true
  validates :email, :username, uniqueness: true

  before_validation :create_user_name

  def create_user_name
    self.username = email.split("@")[0]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_in
    unless session[:user_id].nil?
      redirect_to '/dashboard/show'
    end
  end

  def create_user

  end

  def create_session
    user = User.find_by_email(params[:email])
    if !user.nil? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/dashboard/show'
    else
      flash[:error] = "Your Credentials are invalid"
      render 'users/sign_in'
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/sign_in.html.erb
<div class="container">
  <div class="row">
    <div class="jumbotron col-md-6 col-md-offset-3">
      <%= form_tag(create_session_path, class: 'display-inline') do %>
        <div class='form-group'>
          <%= email_field_tag('email', params[:email], class: 'form-control', placeholder: 'Email') %>
        </div>
        <div class='form-group'>
          <%= password_field_tag('password', "", class: 'form-control', placeholder: 'Password') %>
        </div>
        <%= submit_tag "Submit", class: 'btn btn-success' %>
      <% end %>
      <div class='display-inline float-right'>
        <%= link_to "Create new account", new_account_path %>
      </div>
    </div>
  </div>
</div>