config/routes.rb
Rails.application.routes.draw do

  root to: 'users#sign_in'
  
  scope path: '/users', controller: :users do
    get 'sign_in' => :sign_in, as: 'login'
    post 'create_session' => :create_session, as: 'create_session'
    get 'logout' => :logout
  end

  scope accounts: '/accounts', controller: :accounts do
    get 'new' => :new, as: 'new_account'
    post 'create' => :create, as: 'create_account'
  end

  scope path: '/dashboard', controller: :dashboard do
    get 'show' => :show, as: 'dashboard_show'
  end

  scope path: '/streams', controller: :streams do
    get 'show' => :show, as: 'show_streams'
    get 'new' => :new, as: 'new_stream'
    post 'create' => :create, as: 'create_stream'
  end

  scope path: '/remote_devices', controller: :remote_devices do
    post 'create' => :create, as: 'create_remote_device'
  end

  scope path: '/api', controller: :data do
    post 'new_data' => :create
    post 'telegram' => :index
    post 'telegram_devices' => :devices
  end


end

app/models/stream.rb
class Stream < ActiveRecord::Base
  belongs_to :remote_device
  has_many :stream_data

  validates :name, :stream_type, presence: true

  before_save :create_unique_id

  def create_unique_id
    self.unique_id = Digest::SHA256.hexdigest(UUID.generate)
  end
  
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController

  def show
    @remote_devices = []
    @current_user.accounts.each do |account|
      account.remote_devices.each do |remote_device|
        @remote_devices << remote_device
      end
    end
  end

  def create
    st = Stream.create({:name => params[:stream_name], :stream_type => params[:stream_type], :remote_device_id => params[:remote_device_id]})
    unless st.errors.blank?
      flash[:error] = "Error while creating stream"
    end
    redirect_to '/streams/show'
  end

end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/streams/show.html.erb
<%= render '/partials/navbar' %>
<div class="container">
  <% unless @remote_devices.nil? %>
    <%  @remote_devices.each do |remote_device| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= remote_device.name %></h3>
          <h5>Unique ID: <%= remote_device.unique_id %></h5>
        </div>
        <div class="panel-body">
            <% unless remote_device.streams.nil? %>
              <div class="col-md-3"><b>Stream Name</b></div>
              <div class="col-md-3"><b>Stream Type</b></div>
              <div class="col-md-6"><b>Unique ID</b></div>            
              <% remote_device.streams.each do |stream|%>
                <div class="col-md-3"><%= stream.name %></div>
                <div class="col-md-3"><%= stream.stream_type %></div>
                <div class="col-md-6"><%= stream.unique_id %></div>
              <% end %>
            <% end %>
            <div class="col-md-12">
            <hr />
            <%= form_tag( create_stream_path , class: 'form-inline') do %>
                <div class="form-group">
                  <input class="form-control" name="stream_name" id="stream_name" placeholder="Stream Name">
                </div>
                <div class="form-group">
                  <input class="form-control" name="stream_type" id="stream_type" placeholder="Stream Type">
                </div>
                <div class="form-group">
                  <%= text_field_tag "remote_device_id", remote_device.id, class: "form-control", style: "display: none" %>
                </div>
                <button type="submit" class="btn btn-success">Create</button>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="well">
    <%= form_tag( create_remote_device_path, class: 'form-inline') do %>
      <div class="form-group">
        <input class="form-control" id="remote_device_name" name="remote_device_name" placeholder="Remote Device Name">
      </div>
      <div class="form-group">
        <input class="form-control" id="location_name" name="location_name" placeholder="Location Name">
      </div>
      <div class="form-group">
        <input class="form-control" id="latitude" name="latitude" placeholder="Latitude">
      </div>
      <div class="form-group">
        <input class="form-control" id="longitude" name="longitude" placeholder="Longitude">
      </div>
      <div class="form-group">
        <%= text_field_tag "account_id", @current_user.user_account_relations.where(:relation_type => "admin")[0].account.id, class: "form-control", style: "display: none" %>
      </div>
      <button type="submit" class="btn btn-success">Create</button>
    <% end %>
  </div>
</div>