config/routes.rb
Rails.application.routes.draw do

  root to: 'users#sign_in'
  
  scope path: '/users', controller: :users do
    get 'sign_in' => :sign_in, as: 'login'
    post 'create_session' => :create_session, as: 'create_session'
    get 'logout' => :logout
  end

  scope accounts: '/accounts', controller: :accounts do
    get 'new' => :new, as: 'new_account'
    post 'create' => :create, as: 'create_account'
  end

  scope path: '/dashboard', controller: :dashboard do
    get 'show' => :show, as: 'dashboard_show'
  end

  scope path: '/streams', controller: :streams do
    get 'show' => :show, as: 'show_streams'
    get 'new' => :new, as: 'new_stream'
    post 'create' => :create, as: 'create_stream'
  end

  scope path: '/remote_devices', controller: :remote_devices do
    post 'create' => :create, as: 'create_remote_device'
  end

  scope path: '/api', controller: :data do
    post 'new_data' => :create
    post 'telegram' => :index
    post 'telegram_devices' => :devices
  end


end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :user_account_relations
  has_many :users, through: :user_account_relations
  has_many :remote_devices

  validates :name, presence: true

  before_save :generate_api_key

  def generate_api_key
    self.api_key = Digest::SHA256.hexdigest(UUID.generate)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    timezones_file = File.open("lib/assets/timezones.txt").read.split("\n")
    @timezones = timezones_file.map{|x| {:name => x.split("=>")[0], :id => x.split("=>")[1]}}
  end

  def create
    account = Account.create({:name => params[:name], :timezone => params[:timezone]})
    if account
      user = account.users.create(
        {
          :name => params[:name], 
          :email => params[:email], 
          :password => params[:password], 
          :password_confirmation => params[:password]
        })
      if user
        relation = user.user_account_relations.last
        relation.relation_type = "admin"
        relation.save
        session[:user_id] = user.id
        redirect_to '/dashboard/show'
      else
        flash[:error] = "Invalid user"
        render '/create'
      end
    else
      flash[:error] = "Account name can't be blank"
      render '/create'
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/new.html.erb
<div class="container">
  <div class="row">
    <div class="jumbotron col-md-6 col-md-offset-3">
      <%= form_tag(create_account_path, class: 'display-inline', method: 'POST') do %>
        <div class='form-group'>
          <%= text_field_tag('name', params[:name], class: 'form-control', placeholder: 'Name') %>
        </div>
        <div class='form-group'>
          <%= email_field_tag('email', params[:email], class: 'form-control', placeholder: 'Email') %>
        </div>
        <div class='form-group'>
          <%= password_field_tag('password', "", class: 'form-control', placeholder: 'Password') %>
        </div>
        <div class="form-group">
          <%= select_tag :timezone, options_for_select(@timezones.collect{|c| [c[:name], c[:id]]}), class: 'form-control' %>
        </div>
        <%= submit_tag "Submit", class: 'btn btn-success' %>
      <% end %>
      <div class='display-inline float-right'>
        <%= link_to "Login", login_path %>
      </div>
    </div>
  </div>
</div>